# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = '1'
    vb.memory = '1024'
  end
  config.vm.box_check_update = false

  config.vm.synced_folder "../", "/vagrant"

  config.vm.define 'master' do |master|
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.hostname = "master"
    master.ssh.port = "2222"
  end

  (1..2).each do |i|
      config.vm.define "slave#{i}" do |slave|
        slave.vm.network :forwarded_port, guest: 22, host: "227#{i}".to_i, id: 'ssh'
        slave.vm.network "private_network", ip: "192.168.33.2#{i}"
        slave.vm.hostname = "slave#{i}"
      end
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'playbooks/main.yml'
    ansible.galaxy_role_file = 'playbooks/requirements.yml'
	ansible.inventory_path = 'ansible/inventory_vagrant.ini'
  end

end